### PR TITLE
Markdown syntax updates and typo fixes

### PR DESCRIPTION
**Pull request by cdeboever3**
I've gone through this markdown document and fixed some markdown
problems. There were several areas where code blocks were messed up due
to indenting. I also tried to apply consistent use of code markups. I
fixed several small typos and standardized some spelling and text
formatting for phrases or names used throughout the document. I did not
(intentionally) change any content.

This PR goes beyond #12 but it may be worth merging both.

This PR is intended to fulfill my post-training lesson contribution. I also believe that @ErinBecker mentioned at our training that the genomics module is going to be overhauled - I'd be glad to participate in that when the time comes.

### CODE REVIEW

**Comment by tracykteal** [comment]
Thanks for these updates. We'll go through and review them. Would be great to have you involved in the genomics lesson! There's [a form](https://docs.google.com/forms/d/e/1FAIpQLSfm4aMOdVt0kDLGzEaAAyhsjoOBcjL8s7TUnXxw-apvxemhmg/viewform?c=0&w=1) we're using to collect interest

**Comment by ErinBecker** [comment]
Thanks @cdeboever3 and sorry it's taken a long while to get to this PR. I see that there are conflicts with the fixes you proposed. I'll go through those today and resolve and get this merged!

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/wrangling-genomics/pull/48.

**Comment by ErinBecker** [comment]
Thanks @cdeboever3!

**Comment by cdeboever3** [comment]
No problem thanks for the merge!

**Pull request closed without merging**
