### PR TITLE
Fix answer to FastQC question in quality control lesson

### PR DESCRIPTION
**Pull request by shiltemann**
I believe the answer to the FastQC results interpretation exercise had it backwards when it states:

*`SRR097977` and `SRR098027` are the best. The other four samples are all pretty bad.*

These two samples looked the worst when I ran it, and are also the only two not to pass FastQC's test for per-base quality (as also confirmed by the summary.txt question later on in the tutorial) so I inverted the answer. Also two small typos.

### CODE REVIEW

**Comment by fpsom** [comment]
Thanks @shiltemann ! This is indeed a very good point. We are actually in the process of bringing out a new major release of the entire lesson, probably sometime next week, so, it that is ok with you, I'll refrain from merging until we get to the new version and re-assess.

**Comment by shiltemann** [comment]
@fpsom ah that is really great, sure that is fine by me, I look forward to seeing the new lesson!

**Comment by ErinBecker** [comment]
@fpsom - I know that the new version of the lesson uses different sequencing files. Can this issue be closed?

**Comment by fpsom** [comment]
Yes, indeed. We are using a completely new dataset, so this issue can be safely closed. Thanks @shiltemann for pointing out the issue in the first place - it helped us recheck the exercises for the new version!

**Pull request closed without merging**
