### PR TITLE
Updated 00readQC.md formatting, typos, consistency

### PR DESCRIPTION
**Pull request by hoytpr**
**Only one file is changed in this PR: 00readQC.md**
Changed typos, spacing, formatting, increased consistency
removed unused image
Any other visible commits are cleaning up our repo and should not change anything else.

### CODE REVIEW

**Comment by lexnederbragt** [comment]
This PR introduces a new image but nothing else (see https://github.com/datacarpentry/wrangling-genomics/pull/46/files). I suspect that is not the intention?

**Comment by hoytpr** [comment]
You are correct. That image is for a genomics module we're working on and I'm not sure how this happened. A new PR will be made for 00readQC.md

**Comment by ErinBecker** [comment]
The changes to  00readQC.md look good to me, but I still see an extra image file in the PR. @hoytpr could you remove the image004.gif file? Please let us know if you'd like a hand!

**Comment by ErinBecker** [comment]
Also noting that this PR address the `cat` portion of https://github.com/datacarpentry/wrangling-genomics/issues/8

**Comment by ErinBecker** [comment]
@hoytpr - Because we had multiple pending PRs making formatting changes to 00-readQC.md, I went ahead and resolved conflicts on this one and got it merged. We can take care of the extra image file after merging. Thanks again!

**Comment by hoytpr** [comment]
@ErinBecker <https://github.com/erinbecker> please remove that dang 
image file. I've tried twice and can't seem to get it right.
Thank you very much.
peter

**Pull request merged**
