### PR TITLE
 move to shell-genomics

### PR DESCRIPTION
**Pull request by aschuerch**
This moves introduction of the FASTQ format to the start of the workshop, according to the discussion at https://github.com/datacarpentry/shell-genomics/issues/136. Relates to https://github.com/datacarpentry/shell-genomics/pull/164

### CODE REVIEW

**Comment by fpsom** [comment]
Thanks @aschuerch ! Has this part already been moved to the shell genomics lesson? If so, it looks good to me, so it can be merged.

**Comment by aschuerch** [comment]
It's in https://github.com/datacarpentry/shell-genomics/pull/164. Please wait for that to be approved/merged.

**Comment by taylorreiter** [comment]
+1!

**Comment by aschuerch** [comment]
ATM it is both in shell genomics and wrangling

**Comment by ErinBecker** [comment]
I just taught this last week and thought that the FASTQ format explanation was in a good place. It didn't seem to be problematic to me. Yes, the quality of the read that is used as an example is really low, but that actually worked out well - got a little chuckle out of the audience. I propose we leave things as they are now and close this issue. @fpsom - what do you think?

**Comment by fpsom** [comment]
As I haven't taught the lesson yet in the context of an actual workshop, I'll definitely defer to your judgement @ErinBecker! And in any case, having the same topic (slightly varied) twice is not really an issue for me. :)

So, in short, +1 to closing the issue.

**Pull request closed without merging**
