### PR TITLE
Added instructions for self-study to README

### PR DESCRIPTION
**Pull request by lexnederbragt**
Addresses #75. I am not entirely satisfied yet as I would have liked to write 'all data needed for the lesson can be downloaded from here' - I am not sure whether the file linked too has in fact all data that is needed...

### CODE REVIEW

**Comment by fpsom** [comment]
As far as I know, there has been the decision to completely remove the `tar.gz` file - which means that the only option right now is either through the direct source, or through the AMI image. Maybe @ErinBecker or @crazyhottommy have a better idea on that?

**Comment by fpsom** [comment]
Thanks @lexnederbragt @ErinBecker ! I'm merging now as all the information is there (at least so it seems to me).

**Comment by ErinBecker** [comment]
@lexnederbragt - Thanks for putting this together. Based on the [several conversations](https://github.com/datacarpentry/genomics-workshop/issues/31) that have been going on in the different genomics repos about data accessibility and software installation, we've opted to centralize all of this information on the [genomics-workshop setup page](https://github.com/datacarpentry/genomics-workshop/issues/31). This way, there will be only one location to update in the event of changes to data availability and software used. 

@tracykteal is currently setting up the data to be available on OSF in addition to the AMI (for self-directed learners who don't want to set up an AMI themselves). 

We have also just [updated the AMI](https://github.com/datacarpentry/genomics-workshop/pull/34), including removing the variant_calling.tar.gz file. 

I suggest we remove the new language on this page about self-study and instead link learners back to the setup page for the workshop overview. It isn't yet complete (need to add the data link to OSF), but it's the most up-to-date location of the information so far.

**Comment by lexnederbragt** [comment]
Sure, and your solution (OSF + AMI) looks great!

**Comment by ErinBecker** [comment]
Thanks @lexnederbragt. I've reverted the merge now. Tracy has added links to the data and instructions on accessing it here: http://www.datacarpentry.org/genomics-workshop/setup/

**Comment by tracykteal** [comment]
Data transfer is still in progress, but here's the OSF project for the Genomics data

https://osf.io/ycu8j/

Seems to work well for making the data available.

**Comment by tracykteal** [comment]
I also used this handy new OSFclient for the data transfer. http://osfclient.readthedocs.io/en/latest/ Thanks @betatime and @ctb

**Pull request merged**
