### PR TITLE
Workthrough for update to AMI

### PR DESCRIPTION
**Pull request by ErinBecker**
This PR works through each of the episodes in the wrangling lesson and updates code and output chunks based on changes to the AMI.

### CODE REVIEW

**Comment by ErinBecker** [comment]
The biggest change here is the removal of the variant_calling.tar.gz file. Now we have the learners create the script piece by piece in the lesson. We also provide a complete script (as well as all of the output files) on the AMI in a `solutions` directory in case the learners run into any problems.

**Comment by tracykteal** [comment]
Thanks this looks good to me, and I know reflects the new AMI setup. Should I wait to merge until we have the new AMI listed as the one to use?

**Comment by ErinBecker** [comment]
Yes please. I'm still working on generating the solutions files for the new AMI. Should be ready sometime tomorrow.

**Comment by tracykteal** [comment]
The information in genomics-workshop/setup.md has been updated with the new AMI

https://github.com/datacarpentry/genomics-workshop/pull/34

So, merging this PR

**Pull request merged**
